### ISSUE TITLE
Printing does not work

### ISSUE THREAD

**Issue by antoinepairet** [legalthings/angular-pdfjs-viewer#4]
Thanks for making `angular-pdfjs-viewer`. It looking great.

There seems to be an issue with printing. PDF.js complains when calling `renderProgress`, it crashes because the template is lacking 2 divs:
1. printContainer
2. mozPrintCallback-shim

The renderProgress function searches the `mozPrintCallback-shim`, but cannot find it. It is `null` and 

Crash:
`var progressContainer = document.getElementById('mozPrintCallback-shim');` is null...
One cannot call `querySelector` on it.
![screen shot 2016-02-13 at 00 10 46](https://cloud.githubusercontent.com/assets/5238592/13023145/4587052a-d1e6-11e5-804d-1e4454f6994b.png)

Original viewer template:
![screen shot 2016-02-13 at 00 07 12](https://cloud.githubusercontent.com/assets/5238592/13023107/df4c5152-d1e5-11e5-8b79-b9801869af61.png)

Is the solution as simple as adding the missing divs to the template?

**Comment by antoinepairet** [comment]
It might be as simple as updating the `viewer.html` in your vendor folder (not on GitHub).
see: https://github.com/legalthings/angular-pdfjs-viewer/blob/master/Gruntfile.js#L21

**Comment by moesjarraf** [comment]
Yes I believe updating the `viewer.html` file should solve the problem. As you can see [here](https://github.com/legalthings/pdf.js-viewer/blob/master/viewer.html#L288) the piece of code in your screenshot is missing in our viewer file. Could you test if the problem is solved by adding that snippet of code below `<!-- outerContainer -->`? If it fixes it, feel free to make a pull request at https://github.com/legalthings/pdf.js-viewer

**Comment by kegster** [comment]
I'm having this issue as well with chrome and FF. The viewer.html that I downloaded from your responses here still is missing those dis.

I've added the divs myself but I don't see them showing up.

**Comment by moesjarraf** [comment]
It should be fixed now after running a `bower update` in your project.

**Comment by kegster** [comment]
This solution partially fixed the problem. While the print button now works, it doesn't do a nice print of the document only. It shows as if someone tried to print the website.

Any ideas?
